blank_issues_enabled: false
contact_links:
    -   name: Laravel issue
        url: https://github.com/laravel/framework/issues
        about: 'If you have a question about your Laravel implementation, ask it in your Laravel project.'
