name: Tests

on: [ push, pull_request ]

jobs:
  
  sqlite:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true
      matrix:
        php: [ "8.2", "8.3" ]
        laravel: [ "10.0", "11.0" ]
    
    name: PHP ${{ matrix.php }}, Laravel ${{ matrix.laravel }}, SQLite 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, pdo_mysql, pdo_pgsql
          coverage: xdebug

      - name: Install dependencies
        run: composer require laravel/framework:^${{ matrix.laravel }}

      - name: Execute tests
        run: composer test
  
#  mysql:
#    runs-on: ubuntu-latest
#    
#    strategy:
#      fail-fast: true
#      matrix:
#        php: [ "8.2", "8.3" ]
#        laravel: [ "10.0", "11.0" ]
#        mysql: [ "5.7", "8" ]
#    
#    name: PHP ${{ matrix.php }}, Laravel ${{ matrix.laravel }}, PostgreSQL ${{ matrix.psql }}
#    
#    services:
#      mysql:
#        image: mysql:${{ matrix.mysql }}
#        env:
#          MYSQL_ROOT_PASSWORD: root
#          MYSQL_DATABASE: default
#        ports:
#          - 3306:3306
#        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
#    
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: ${{ matrix.php }}
#          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, pdo_mysql, pdo_pgsql
#          coverage: xdebug
#
#      - name: Install dependencies
#        run: composer require laravel/framework:^${{ matrix.laravel }}
#
#      - name: Execute tests
#        run: composer test
#        env:
#          DB_CONNECTION: mysql
#          MYSQL_HOST: 127.0.0.1
#
#  postgres:
#    runs-on: ubuntu-latest
#    
#    strategy:
#      fail-fast: true
#      matrix:
#        php: [ "8.2", "8.3" ]
#        laravel: [ "10.0", "11.0" ]
#        psql: [ "12", "13", "14", "15", "16" ]
#    
#    name: PHP ${{ matrix.php }}, Laravel ${{ matrix.laravel }}, PostgreSQL ${{ matrix.psql }}
#    
#    services:
#      postgres:
#        image: postgres:${{ matrix.psql }}-alpine
#        ports:
#          - 5432:5432
#        env:
#          POSTGRES_DB: default
#          POSTGRES_USER: root
#          POSTGRES_PASSWORD: root
#    
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: ${{ matrix.php }}
#          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, pdo_mysql, pdo_pgsql
#          coverage: xdebug
#
#      - name: Install dependencies
#        run: composer require laravel/framework:^${{ matrix.laravel }}
#
#      - name: Execute tests
#        run: composer test
#        env:
#          DB_CONNECTION: pgsql
#          PGSQL_HOST: 127.0.0.1
